### ISSUE TITLE
MAINTENANCE: upper limits on dependencies

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyconceptev#108]
Pinging @SMoraisAnsys since he is the only one I know working in this package...

https://github.com/ansys/pyconceptev/blob/4b3c8c6386983c31a83888386f590f4741a0a21d/pyproject.toml#L35-L43

Is there really a need to put the cap on all these dependencies (I'm referring to the upper limits). Some libraries are using above https 0.27 and this package prevents them from using it. It is in general not a good practice to cap such standard dependencies... See other poetry-based projects:

https://github.com/ansys/pyacp/blob/90189482a8ad4cfc74057282bc84fb769716a4e6/pyproject.toml#L35-L46

Can we get this solved and get out a new patch release?

**Comment by SMoraisAnsys** [comment]
@RobPasMue This should be handled with #109.

Non main dependencies haven't been updated though, let us know if that's an issue

**Comment by RobPasMue** [comment]
Nope, that's not a problem - as long as the main deps are not capped on the upper limit I'm happy  :)
